apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: goserver-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: goserver
  minReplicas: 1
  maxReplicas: 30
  targetCPUUtilizationPercentage: 25 # Normalmente em 75% ou 80% -> Depende do tempo que o POD demora para subir
